"""
Regenerates apps/web/components/ui/logo-paths.ts: the motology wordmark and
the "m●" symbol as fixed SVG paths, drawn from Inter Display (opsz 32).

The first "o" of the wordmark is replaced by the price point: a lime dot,
drawn slightly larger than the o so it reads at the same optical size.

    python -m venv .venv && .venv/bin/pip install fonttools brotli
    .venv/bin/python scripts/brand/build_logo.py   # from motology/
"""
import json
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'node_modules/@fontsource-variable/inter/files/inter-latin-opsz-normal.woff2'
OUT = ROOT / 'apps/web/components/ui/logo-paths.ts'

WORD = 'motology'
WEIGHT = 640
TRACKING = -0.025  # em
DOT_SCALE = 1.06   # optical: a filled disc looks smaller than an o of the same width
TOP, BOTTOM = -1560, 450  # ascender of t/l to descender of g/y, font units


def rounded(cmds: str) -> str:
    out = []
    for tok in cmds.replace('M', ' M ').replace('L', ' L ').replace('Q', ' Q ').replace('Z', ' Z ').replace('C', ' C ').replace('H', ' H ').replace('V', ' V ').split():
        try:
            out.append(f'{float(tok):.0f}')
        except ValueError:
            out.append(tok)
    return ' '.join(out).replace(' Z', 'Z')


def bounds(gs, name):
    pen = BoundsPen(gs)
    gs[name].draw(pen)
    return pen.bounds


def wordmark(font):
    gs, cmap, hmtx = font.getGlyphSet(), font.getBestCmap(), font['hmtx']
    upm = font['head'].unitsPerEm
    x, parts, dot, seen_o = 0.0, [], None, False
    for ch in WORD:
        g = cmap[ord(ch)]
        if ch == 'o' and not seen_o:
            seen_o = True
            xmin, ymin, xmax, ymax = bounds(gs, g)
            dot = (x + (xmin + xmax) / 2, -(ymin + ymax) / 2, (xmax - xmin) / 2 * DOT_SCALE)
        else:
            pen = SVGPathPen(gs)
            gs[g].draw(TransformPen(pen, (1, 0, 0, -1, x, 0)))
            parts.append(pen.getCommands())
        x += hmtx[g][0] + TRACKING * upm
    width = x - TRACKING * upm
    return rounded(' '.join(parts)), width, dot


def symbol(font):
    """"m●" centred in a 1000-unit tile."""
    gs, cmap = font.getGlyphSet(), font.getBestCmap()
    m, o = cmap[ord('m')], cmap[ord('o')]
    mx0, my0, mx1, my1 = bounds(gs, m)
    ox0, _, ox1, _ = bounds(gs, o)
    r = (ox1 - ox0) / 2 * 0.8
    gap = 70
    total = (mx1 - mx0) + gap + 2 * r
    size = 1000
    k = size * 0.62 / total
    ox = (size - total * k) / 2 - mx0 * k
    base = size / 2 + (my1 - my0) * k / 2 + 8
    pen = SVGPathPen(gs)
    gs[m].draw(TransformPen(pen, (k, 0, 0, -k, ox, base)))
    return rounded(pen.getCommands()), (ox + (mx1 + gap + r) * k, base - r * k, r * k)


def main():
    font = instantiateVariableFont(TTFont(SRC), {'opsz': 32, 'wght': WEIGHT})
    d, width, (cx, cy, r) = wordmark(font)
    sd, (scx, scy, sr) = symbol(instantiateVariableFont(TTFont(SRC), {'opsz': 32, 'wght': 700}))
    OUT.write_text(f"""// Generated by scripts/brand/build_logo.py. Do not edit by hand.

/** The motology wordmark, with the first "o" left out for the price-point dot. */
export const WORDMARK = {{
  viewBox: '0 {TOP} {width:.0f} {BOTTOM - TOP}',
  width: {width:.0f},
  height: {BOTTOM - TOP},
  d: {json.dumps(d)},
  dot: {{ cx: {cx:.0f}, cy: {cy:.0f}, r: {r:.0f} }},
}} as const

/** "m●" in a 1000-unit tile. */
export const SYMBOL = {{
  d: {json.dumps(sd)},
  dot: {{ cx: {scx:.0f}, cy: {scy:.0f}, r: {sr:.0f} }},
}} as const
""")
    print(f'wrote {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
